manage_etc_hosts: false
users:
  - default
  - name: labrat
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys: 
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK8DkrwnXIab+CwG87mTqvS6Ed6XmY9/jd3xsseM1RI2 I550271@FVFF9527Q05N


runcmd:
 - [ git, clone, https://github.com/owaldhorst-hka/CPUnetPLOT ]
 - [ cd, /home/labrat]
 - [ git, clone, https://github.com/owaldhorst-hka/kn1lab ]
 - [ mkdir, -m, 777, /home/labrat/Maildir]
 - [ mkdir, -m, 777, /home/labrat/Maildir/new]
 - [ mkdir, -m, 777, /home/labrat/Maildir/cur]
 - [ mkdir, -m, 777, /home/labrat/Maildir/tmp]
